name: 'Jira description to pr'
description: 'Add jira description to Pull request'
branding:
  icon: "check-circle"
  color: "purple"
inputs:
  token:
    description: "Github access token"
    required: true
  jiraId:
    description: "Jira issue id"
    required: true
  orgUrl: 
    description: "organization's jira url"
    required: true
  customfields: 
    description: "Json data for the custom fields"
    required: true
  jiraToken:
    description: "Jira token"
    required: true
  jiraUsername:
    description: "Jira username"
    required: true
  sonarQubeUrl:
    description: "organization's sonarqube url"
    required: false
  filesChanges:
    description: "files that were changed during PR creation"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'