name: Update PR Description with Jira Title
on:
 pull_request:
   types: [opened,synchronize,reopened]

jobs:
 update_pr_description:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Split Jira id from branch name
       id: extract_branch_name
       run: |
           branch_name="${{github.event.pull_request.head.ref}}"
           first_part=$(echo "$branch_name" | cut -d'/' -f1)
           echo "::set-output name=jira_id::$first_part"
     - name: print context
       id: jira
       run: |
             echo '${{toJSON(github)}}'
     - name: Get changed files
       id: files
       run: |
           GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
           API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
           CHANGED_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $API_URL | jq -r '.[] | .filename')
 
           # Extract only the last part of the file paths (file names without directories)
           CHANGED_FILES_FORMATTED=""
           while IFS= read -r line; do
             FILENAME=$(basename "$line")
             CHANGED_FILES_FORMATTED+="\n- $FILENAME"
           done <<< "$CHANGED_FILES"
 
           echo "::set-output name=changed_files::$CHANGED_FILES_FORMATTED"
           echo "Changed Files:"
           echo "$CHANGED_FILES_FORMATTED"
     - name: action test 
       id: javascript
       uses: ./
       with:
          token: ${{secrets.GITHUB_TOKEN}}
          jiraId: SWIT-309
          orgUrl: https://anywhereworks.atlassian.net
          jiraToken: ${{secrets.JIRA_API_TOKEN}}
          jiraUsername: ${{secrets.JIRA_USERNAME}}
          sonarQubeUrl: https://sonar.anywhere.co
          customfields: '{"customfield123": "developer testing", "customfield433": "acceptance criteria"}'
          filesChanges: ${{steps.files.outputs.changed_files}}
          
    
 
             


